
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";




import AboutUs from "./pages/AboutUs.tsx";
import Admin from "./pages/Admin.tsx";
import AdminDocs from "./pages/AdminDocs.tsx";
import AlbumDetail from "./pages/AlbumDetail.tsx";
import App from "./pages/App.tsx";
import BerdieConsultant from "./pages/BerdieConsultant.tsx";
import BugRepro from "./pages/BugRepro.tsx";
import CampaignAdmin from "./pages/CampaignAdmin.tsx";
import CommunityImpact from "./pages/CommunityImpact.tsx";
import ContactUs from "./pages/ContactUs.tsx";
import CreateBlogPost from "./pages/CreateBlogPost.tsx";
import Donate from "./pages/Donate.tsx";
import Feedback from "./pages/Feedback.tsx";
import Feedbackadmin from "./pages/Feedbackadmin.tsx";
import FormSubmissions from "./pages/FormSubmissions.tsx";
import History from "./pages/History.tsx";
import Impact from "./pages/Impact.tsx";
import InternalCRM from "./pages/InternalCRM.tsx";
import MakingDifference from "./pages/MakingDifference.tsx";
import Members from "./pages/Members.tsx";
import NewsAndStories from "./pages/NewsAndStories.tsx";
import OurStory from "./pages/OurStory.tsx";
import Pictures from "./pages/Pictures.tsx";
import Resources from "./pages/Resources.tsx";
import ShareStory from "./pages/ShareStory.tsx";
import SuccessStories from "./pages/SuccessStories.tsx";
import TestForms from "./pages/TestForms.tsx";
import Unsubscribe from "./pages/Unsubscribe.tsx";
import Videos from "./pages/Videos.tsx";
import Vision from "./pages/Vision.tsx";
import WhoIsBertie from "./pages/WhoIsBertie.tsx";

export const userRoutes: RouteObject[] = [



	{ path: "/about-us", element: <AboutUs /> },
	{ path: "/aboutus", element: <AboutUs /> },
	{ path: "/admin", element: <Admin /> },
	{ path: "/admin-docs", element: <AdminDocs /> },
	{ path: "/admindocs", element: <AdminDocs /> },
	{ path: "/album-detail", element: <AlbumDetail /> },
	{ path: "/albumdetail", element: <AlbumDetail /> },
	{ path: "/", element: <App /> },
	{ path: "/berdie-consultant", element: <BerdieConsultant /> },
	{ path: "/berdieconsultant", element: <BerdieConsultant /> },
	{ path: "/bug-repro", element: <BugRepro /> },
	{ path: "/bugrepro", element: <BugRepro /> },
	{ path: "/campaign-admin", element: <CampaignAdmin /> },
	{ path: "/campaignadmin", element: <CampaignAdmin /> },
	{ path: "/community-impact", element: <CommunityImpact /> },
	{ path: "/communityimpact", element: <CommunityImpact /> },
	{ path: "/contact-us", element: <ContactUs /> },
	{ path: "/contactus", element: <ContactUs /> },
	{ path: "/create-blog-post", element: <CreateBlogPost /> },
	{ path: "/createblogpost", element: <CreateBlogPost /> },
	{ path: "/donate", element: <Donate /> },
	{ path: "/feedback", element: <Feedback /> },
	{ path: "/feedbackadmin", element: <Feedbackadmin /> },
	{ path: "/form-submissions", element: <FormSubmissions /> },
	{ path: "/formsubmissions", element: <FormSubmissions /> },
	{ path: "/history", element: <History /> },
	{ path: "/impact", element: <Impact /> },
	{ path: "/internal-crm", element: <InternalCRM /> },
	{ path: "/internalcrm", element: <InternalCRM /> },
	{ path: "/making-difference", element: <MakingDifference /> },
	{ path: "/makingdifference", element: <MakingDifference /> },
	{ path: "/members", element: <Members /> },
	{ path: "/news-and-stories", element: <NewsAndStories /> },
	{ path: "/newsandstories", element: <NewsAndStories /> },
	{ path: "/our-story", element: <OurStory /> },
	{ path: "/ourstory", element: <OurStory /> },
	{ path: "/pictures", element: <Pictures /> },
	{ path: "/resources", element: <Resources /> },
	{ path: "/share-story", element: <ShareStory /> },
	{ path: "/sharestory", element: <ShareStory /> },
	{ path: "/success-stories", element: <SuccessStories /> },
	{ path: "/successstories", element: <SuccessStories /> },
	{ path: "/test-forms", element: <TestForms /> },
	{ path: "/testforms", element: <TestForms /> },
	{ path: "/unsubscribe", element: <Unsubscribe /> },
	{ path: "/videos", element: <Videos /> },
	{ path: "/vision", element: <Vision /> },
	{ path: "/who-is-bertie", element: <WhoIsBertie /> },
	{ path: "/whoisbertie", element: <WhoIsBertie /> },

];
